# These are supported funding model platforms
#
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button

github: Akichoooo
open_collective: subclaw
ko_fi: akichoooo
tidelift: "npm/leave-none"
community_bridge: subclaw
liberapay: akichoooo
issuehunt: akichoooo
lfx_crowdfunding: subclaw
polar: subclaw
buy_me_a_coffee: akichoooo
thanks_dev: akichoooo
custom: ["https://www.paypal.me/akichoooo"]
